on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
  pull_request:        # - A pull-request is openned or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  main:
    strategy:
      
      fail-fast: false # Don't stop all the workflows when one of them fails.
    
      matrix:
        os: [windows-2016] # List of GitHuh Actions platform to run the workflow on

    runs-on: ${{ matrix.os }} # Run the continous integration workflow on each OS listed in the matrix.
    
    steps:
        # Check-out the repository
      - uses: actions/checkout@v2


      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}

      - run: alr exec -- gnatprove --version
